// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM_katzIx5hYasK4H0z0ui3WDclobnLTc',
    appId: '1:55598441253:web:5f0f788bdbb4f3879870cc',
    messagingSenderId: '55598441253',
    projectId: 'unique-app-game-of-thrones',
    authDomain: 'unique-app-game-of-thrones.firebaseapp.com',
    storageBucket: 'unique-app-game-of-thrones.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcuaw1L2q0c9LHeigmVlFoKZWDjMclM9Q',
    appId: '1:55598441253:android:f5f71ea192378d829870cc',
    messagingSenderId: '55598441253',
    projectId: 'unique-app-game-of-thrones',
    storageBucket: 'unique-app-game-of-thrones.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkDUwpsjXqkUqK-1Lr_1qeIm42UlyLGBQ',
    appId: '1:55598441253:ios:1db9c54fc57a31859870cc',
    messagingSenderId: '55598441253',
    projectId: 'unique-app-game-of-thrones',
    storageBucket: 'unique-app-game-of-thrones.appspot.com',
    iosBundleId: 'com.example.lab5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkDUwpsjXqkUqK-1Lr_1qeIm42UlyLGBQ',
    appId: '1:55598441253:ios:1db9c54fc57a31859870cc',
    messagingSenderId: '55598441253',
    projectId: 'unique-app-game-of-thrones',
    storageBucket: 'unique-app-game-of-thrones.appspot.com',
    iosBundleId: 'com.example.lab5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM_katzIx5hYasK4H0z0ui3WDclobnLTc',
    appId: '1:55598441253:web:f480a465e88676809870cc',
    messagingSenderId: '55598441253',
    projectId: 'unique-app-game-of-thrones',
    authDomain: 'unique-app-game-of-thrones.firebaseapp.com',
    storageBucket: 'unique-app-game-of-thrones.appspot.com',
  );
}
